### ISSUE TITLE
Create an "About" page

### ISSUE THREAD

**Issue by jendiamond** [jendiamond/railsgirlsla-signup#4]
Create a static "About" page.

If not already created:
Create a Static Controller
https://blog.teamtreehouse.com/static-pages-ruby-rails
https://www.railstutorial.org/book/static_pages

---

http://rails-girls-map.herokuapp.com/

http://www.railsbridge.org/

Some stuff about Rails Girls
Rails Girls was born in Finland, founded by Linda Liukas and Karri Saarinen.
Rails Girls was inspired by Railsbridge which was created by Sarah Mei & Sara Allen.

Both Rails Girls and Railsbridge are now global, non-profit volunteer communities inspiring women to be involved in the tech community.

Map of all the Rails Girls Workshops     |     Railsbridge
Rails Girls was founded to help you acquire the tools to build your ideas!

The first steps of learning how to program can be difficult. Our goal is it to help attendees with these first steps. We want to show you that programming is fun and creative and that there is a wonderful community that will support you.

Some women attend to get introduced to the tools and vocabulary of programming for fun and curiosity. Others use it as a launchpad for transitioning careers.

We provide a mentored collaborative learning opportunity where you'll learn sketching, prototyping, basic programming and get introduced to the world of technology.

We are dedicated to providing harassment-free learning experiences for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, or religion.

The Workshop is a hands on introduction to Rails. The workshop has a main focus on women with no previous Ruby on Rails programming experience and who want to be able to build their own applications. The program of the workshop includes an overview of the Rails framework and a practical exercise in which attendees will be guided by coaches through the application building process.

Contact the LA Chapter of Rails Girls at railsgirlsla@gmail.com Follow us on twitter @RailsGirlsLA
Rails Girls International 2010-2016 Contact us or follow us on Twitter and Facebook

---

![screencapture-railsgirls-signup-herokuapp-static-pages-about-2019-05-16-19_54_45](https://user-images.githubusercontent.com/751697/57900164-a2f2a200-7814-11e9-895f-cb37d388ecea.png)

**Comment by kennethlee** [comment]
<img width="1440" alt="Screen Shot 2019-05-31 at 7 07 16 PM" src="https://user-images.githubusercontent.com/1329249/58742187-78d5de00-83d7-11e9-8746-3420e597ebad.png">
